---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
library(tidyverse)
library(ggplot2)
library(lmtest)
library(Hmisc)
library(MASS)
```

```{r}
rm(list = ls())
df = read.table("../data/houseprices.txt", header = TRUE, sep = "\t")
df$Fireplace <- factor(df$Fireplace,
                          levels=c(0,1),
                          labels=c("No", "Yes"))
summary(df)

df_logs = df
df_logs$Acres = log10(df_logs$Acres + 1)
df_logs$Age = log10(df_logs$Age + 1)
summary(df_logs)

```

```{r fig.height=20, fig.width=30}
plot(df)
plot(df_logs)
rcorr(as.matrix(df), type = c("pearson","spearman"))
df_logs.matrix = as.matrix(df_logs)
rcorr(df_logs.matrix, type = c("pearson","spearman"))
```

```{r fig.height=7, fig.width=10}
plot(df$Size, df$Price, xlab="Area (square ft)", ylab="Price ($ ,000)", main="Price by Size")
plot(df$Baths, df$Price, xlab="# of Baths", ylab="Price ($ ,000)", main="Price by Baths")
plot(df$Bedrooms, df$Price, xlab="# of Bedrooms", ylab="Price ($ ,000)", main="Price by Bedrooms")
plot(df$Fireplace, df$Price, xlab="has fireplace", ylab="Price ($ ,000)", main="Price by Fireplace")
plot(df$Acres, df$Price, xlab="log(Acres)", ylab="Price ($ ,000)", main="Price by Acres")
plot(df$Age, df$Price, xlab="Age (Years)", ylab="Price ($ ,000)", main="Price by Age")
     
plot(df_logs$Acres, df_logs$Price, xlab="log(Acres)", ylab="Price ($ ,000)", main="Price by log(Acres)")
plot(df_logs$Age, df_logs$Price, xlab="log(Age) (Years)", ylab="Price ($ ,000)", main="Price by log(Age)")
```

```{r}
df.full_lm <- lm(Price ~ ., data = df_logs)
df.full_res = lm(log(Price) ~ ., data = df_logs)
summary(df.full_lm)
summary(df.full_res)



                # the horizon
```

```{r fig.height=5, fig.width=8}
# log of response
plot(df.full_lm)
plot(df.full_res)
```

```{r fig.height=8, fig.width=10}
interaction.plot(x.factor = df$Size, #x-axis variable
                 trace.factor = df$Fireplace, #variable for lines
                 response = df$Price, #y-axis variable
                 type = "c",
                 fun = median, #metric to plot
                 ylab = "Price",
                 xlab = "Size",
                 col = c("red", "blue"),
                 lty = 1, #line type
                 lwd = 2, #line width
                 trace.label = "Fireplace")

interaction.plot(x.factor = df$Baths, #x-axis variable
                 trace.factor = df$Fireplace, #variable for lines
                 response = df$Price, #y-axis variable
                 fun = median, #metric to plot
                 ylab = "Price",
                 xlab = "Baths",
                 col = c("red", "blue"),
                 lty = 1, #line type
                 lwd = 2, #line width
                 trace.label = "Fireplace")

interaction.plot(x.factor = df$Bedrooms, #x-axis variable
                 trace.factor = df$Fireplace, #variable for lines
                 response = df$Price, #y-axis variable
                 fun = median, #metric to plot
                 ylab = "Price",
                 xlab = "Bedrooms",
                 col = c("red", "blue"),
                 lty = 1, #line type
                 lwd = 2, #line width
                 trace.label = "Fireplace")

interaction.plot(x.factor = df$Acres, #x-axis variable
                 trace.factor = df$Fireplace, #variable for lines
                 response = df$Price, #y-axis variable
                 fun = median, #metric to plot
                 ylab = "Price",
                 xlab = "Acres",
                 col = c("red", "blue"),
                 lty = 1, #line type
                 lwd = 2, #line width
                 trace.label = "Fireplace")

interaction.plot(x.factor = df$Age, #x-axis variable
                 trace.factor = df$Fireplace, #variable for lines
                 response = df$Price, #y-axis variable
                 fun = median, #metric to plot
                 ylab = "Price",
                 xlab = "Age",
                 col = c("red", "blue"),
                 lty = 1, #line type
                 lwd = 2, #line width
                 trace.label = "Fireplace")
```

```{r}
df_logs.lmfireplace = lm(log(Price) ~ Size + Fireplace , data = df_logs)
summary(df_logs.lmfireplace)

noFireplace <- relevel(df_logs$Fireplace, "Yes")
df_logs.lmnofireplace  = lm(log(Price) ~ Size + noFireplace, data = df_logs)
plot(df_logs.lmnofireplace)
```

```{r fig.height=5, fig.width=10}
plot(df$Size, df$Price, xlab="Area (square ft)", ylab="Price ($ ,000)", col=df$Fireplace, main="Price by Size")
abline(df_logs.lmfireplace, col = "red")
#abline(lm(df.full_res$Price ~ df.full_res$age), col = "blue")


ggplot(df_logs) + geom_point(aes(x=Size, y=Price, colour=factor(Fireplace)))
                +  geom_line(color='red',data = df_logs.lmfireplace, aes(x=df_logs.lmfireplace, y=df_logs.lmfireplace$Price))
```

```{r}
#model <- aov()
model.size <- aov(Price ~ Size * Fireplace, data=df_logs)
summary(model.size)
model.baths <- aov(Price ~ Baths * Fireplace, data=df_logs)
summary(model.baths)
model.bedrooms <- aov(Price ~ Bedrooms * Fireplace, data=df_logs)
summary(model.bedrooms)

```
